name: ci

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "**.ipynb"
      - "docs/**"
      - ".readthedocs.yaml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "**.ipynb"
      - "docs/**"
      - ".readthedocs.yaml"
  release:
    types:
      - published

env:
  NWN_ROOT: "${{ github.workspace }}/nwn/"
  SCCACHE_DIR: "${{ github.workspace }}/.sccache/"
  SCCACHE_CACHE_SIZE: "5G"
  SCCACHE_CACHE_MULTIARCH: "1"
  CI_GITHUB_ACTIONS: "1"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-22.04, windows-2019]
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get current date
        if: matrix.os != 'windows-2019'
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get current date
        if: matrix.os == 'windows-2019'
        run: |
          echo "DATE=$(Get-Date -Format yyyy-MM-dd)" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Windows dependencies
      - name: windows - install dependencies
        if: matrix.os == 'windows-2019'
        run: choco install sccache ninja -y

      # macOS Dependencies
      - name: macOS - install sccache
        if: matrix.os == 'macos-14'
        env:
          HOMEBREW_NO_ANALYTICS: "ON"
          HOMEBREW_NO_AUTO_UPDATE: "ON"
        run: brew install sccache

      - name: all - cache sccache
        uses: actions/cache@v4
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: ${{ matrix.os }}-sccache-${{ env.DATE }}
          restore-keys: |
            ${{ matrix.os }}-sccache-

      # nwn
      - name: all - cache nwn
        id: cache-nwn
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/nwn/
          key: cache-nwn-3e02cddcea5d0ae82111a3038f14aef6c14d05d9

      - name: all - download nwn
        if: steps.cache-nwn.outputs.cache-hit != 'true'
        run: |
          curl https://nwn.beamdog.net/downloads/nwnee-dedicated-8193.34.zip -O
          unzip nwnee-dedicated-8193.34.zip -d ${{ github.workspace }}/nwn/
          ls -l ${{ github.workspace }}/nwn/

      - name: Set up MSVC
        if: matrix.os == 'windows-2019'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - uses: pypa/cibuildwheel@v2.22

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
          name: dist-${{ matrix.os }}


      - name: Download Cache from Docker (linux only)
        if: ${{ runner.os == 'Linux' }}
        run: |
          env
          rm -rf "$SCCACHE_DIR"
          mv ./wheelhouse/.sccache "$SCCACHE_DIR"

      - name: sccache stats
        if: ${{ runner.os != 'Linux' }}
        run: sccache --show-stats || true

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: SDist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build, build_sdist]
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: all

      - name: Merge files
        run: |
          mkdir dist
          mv all/*/* dist/.

      - uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
